/**
 * Vercel Serverless Function entry point.
 * This is the source file - the actual deployed file is api/index.mjs
 * generated by the build step using esbuild.
 */
import "dotenv/config";
import express from "express";
import { createExpressMiddleware } from "@trpc/server/adapters/express";
import { registerAuthRoutes } from "../server/_core/oauth";
import { registerFacebookRoutes } from "../server/facebook";
import { registerKbImportRoutes } from "../server/kb-import";
import { appRouter } from "../server/routers";
import { processFollowUps } from "../server/follow-up-worker";
import { createContext } from "../server/_core/context";

const app = express();

app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));

// Auth routes (login/signup)
registerAuthRoutes(app);

// Facebook OAuth & Messenger webhook routes
registerFacebookRoutes(app);

// Knowledge Base import routes (website crawl, PDF upload)
registerKbImportRoutes(app);

// Follow-up cron endpoint
app.post("/api/cron/follow-ups", async (_req, res) => {
  try {
    await processFollowUps();
    res.json({ success: true });
  } catch (error) {
    console.error("[Cron] Follow-up processing failed:", error);
    res.status(500).json({ error: "Follow-up processing failed" });
  }
});

// tRPC API
app.use(
  "/api/trpc",
  createExpressMiddleware({
    router: appRouter,
    createContext,
  })
);

export default app;
